name: Compute metrics
on: [pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        if: ${{ !env.ACT }}
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: .github/mamba.yaml
      - name: install env
        if: ${{ !env.ACT }}
        shell: bash -l {0}
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mamba env update -f environment.yml
      - name: compute metrics
        shell: bash -l {0}
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          PYTHONPATH=. python  scripts/postpro.py
      - name: submit report
        shell: bash -l {0}
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Write your CML report
        run: |
          cat work/submission.md >> report.md
          echo '\n\n' >> report.md
          if test -f "work/GULFSTREAM_nrmse_score.txt"; then
            cat work/GULFSTREAM_nrmse_score.txt >> report.md
            echo '\n\n' >> report.md
            cml-publish work/GULFSTREAM_TS_nRMSE_nadirswot.png --md >> report.md
            cml-publish work/GULFSTREAM_TS_nRMSE_Grad_nadirswot.png --md >> report.md
          fi

          if test -f "work/OSMOSIS_nrmse_score.txt"; then
            cat work/GULFSTREAM_nrmse_score.txt >> report.md
            echo '\n\n' >> report.md
            cml-publish work/GULFSTREAM_TS_nRMSE_nadirswot.png --md >> report.md
            cml-publish work/GULFSTREAM_TS_nRMSE_Grad_nadirswot.png --md >> report.md
          fi
          cml-send-comment report.md
